services:
  postgres:
    container_name: postgres-sql-bn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_net
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - book-social-net
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  book-social-net:
    driver: bridge

volumes:
  postgres:
    driver: local