spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_net
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: alex
    password: 1234
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 354c93f7ae53ab4f9565b98092090cee18f9386b15e06c789c60841729327ad03bb087d5
      expiration: 864000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8080